package proyectologicadifusa;

import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.event.ItemEvent;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.swing.JFrame;

/**
 *
 * @author USER
 */
public class FrameLavadora extends javax.swing.JFrame {

    Font digitalFont;
    // Variables para determinar que fue seleccionado
    boolean color, blanca, deportiva, toallas, sabanas;
    boolean extremadamenteSucia, muySucia, sucia, pocoSucia;
    boolean masiva, grande, mediana, pequena;
    boolean fria, calida, templada;
    
    // Funciones de membresia entradas
    double tipoColor, tipoBlanca, tipoDeportiva, tipoToallas, tipoSabanas;
    double pSucia, _sucia, mSucia, eSucia;
    double cantPequena, cantMediana, cantGrande, cantMasiva;
    double tempFria, tempCalida, tempTemplada;
    // Valores para las funciones de membresia
    double tipoDeRopa;
    double suciedad;
    double cantidadRopa;
    double temperatura;
    
    // Funciones de membresia salidas
    double lavadoMCorto, lavadoCorto, lavadoMedio, lavadoLargo, lavadoMLargo;
    double enjuagueMCorto, enjuagueCorto, enjuagueMedio, enjuagueLargo, enjuagueMLargo;
    double rpmMLento, rpmBajo, rpmMedio, rpmRapido, rpmMRapido;
    
    Random azar = new Random();
    public FrameLavadora() {
        initComponents();
        
        try {
            // Cambia "fonts/tu_fuente.ttf" con la ruta relativa adecuada a tu archivo TTF dentro de tu proyecto
            digitalFont = Font.createFont(Font.TRUETYPE_FONT, new File("src\\Font\\digital-7.ttf")).deriveFont(Font.PLAIN, 48);
        } catch (IOException | FontFormatException ex) {
            // Manejar errores de carga de fuente
            ex.printStackTrace();
        }
        
        jlblTiempoLavado.setFont(digitalFont);
        jlblTiempoLavado.setText("00:00");
        
        jlblTiempoEnjuague.setFont(digitalFont);
        jlblTiempoEnjuague.setText("00:00");
        
        jlblRPM.setFont(digitalFont);
        jlblRPM.setText("0000");
        
        jLabel3.setText("<html><div style='text-align: center;'>Suciedad de<br>la ropa</div></html>");
        jLabel2.setText("<html><div style='text-align: center;'>Cantidad de<br>la ropa</div></html>");
        
    }

/**
     * Creates new form FrameLavadora
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgTipoRopa = new javax.swing.ButtonGroup();
        btgTempRopa = new javax.swing.ButtonGroup();
        btgSuciedadRopa = new javax.swing.ButtonGroup();
        btgCantidadRopa = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jtbColor = new javax.swing.JToggleButton();
        jtbBlanca = new javax.swing.JToggleButton();
        jtbDeportiva = new javax.swing.JToggleButton();
        jtbToallas = new javax.swing.JToggleButton();
        jtbSabanas = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jtbExtSucia = new javax.swing.JToggleButton();
        jtbSucia = new javax.swing.JToggleButton();
        jtbMuySucia = new javax.swing.JToggleButton();
        jtbPocoSucia = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jtbMasiva = new javax.swing.JToggleButton();
        jtbGrande = new javax.swing.JToggleButton();
        jtbMediana = new javax.swing.JToggleButton();
        jtbPequena = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jtbTempFria = new javax.swing.JToggleButton();
        jtbTempCalida = new javax.swing.JToggleButton();
        jtbTempTemplada = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jlblTiempoLavado = new javax.swing.JLabel();
        jlblTiempoEnjuague = new javax.swing.JLabel();
        jlblRPM = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtgbInicio = new javax.swing.JToggleButton();
        jbtnMostrarReglas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Lógica Difusa");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setPreferredSize(new java.awt.Dimension(0, 125));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tipo de ropa");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel6.setBackground(new java.awt.Color(190, 178, 255));

        btgTipoRopa.add(jtbColor);
        jtbColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/COLOR2-removebg-preview.png"))); // NOI18N
        jtbColor.setBorderPainted(false);
        jtbColor.setContentAreaFilled(false);
        jtbColor.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/COLOR1-removebg-preview.png"))); // NOI18N
        jtbColor.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/COLOR3-removebg-preview.png"))); // NOI18N
        jtbColor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbColorItemStateChanged(evt);
            }
        });

        btgTipoRopa.add(jtbBlanca);
        jtbBlanca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/BLANCA2-removebg-preview.png"))); // NOI18N
        jtbBlanca.setBorderPainted(false);
        jtbBlanca.setContentAreaFilled(false);
        jtbBlanca.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/BLANCA1-removebg-preview.png"))); // NOI18N
        jtbBlanca.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/BLANCA3-removebg-preview.png"))); // NOI18N
        jtbBlanca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbBlancaItemStateChanged(evt);
            }
        });

        btgTipoRopa.add(jtbDeportiva);
        jtbDeportiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/DEPORTIVA2-removebg-preview.png"))); // NOI18N
        jtbDeportiva.setBorderPainted(false);
        jtbDeportiva.setContentAreaFilled(false);
        jtbDeportiva.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/DEPORTIVA1-removebg-preview.png"))); // NOI18N
        jtbDeportiva.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/DEPORTIVA3-removebg-preview.png"))); // NOI18N
        jtbDeportiva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbDeportivaItemStateChanged(evt);
            }
        });

        btgTipoRopa.add(jtbToallas);
        jtbToallas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/TOALLAS2-removebg-preview.png"))); // NOI18N
        jtbToallas.setBorderPainted(false);
        jtbToallas.setContentAreaFilled(false);
        jtbToallas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/TOALLAS1-removebg-preview.png"))); // NOI18N
        jtbToallas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/TOALLAS3-removebg-preview.png"))); // NOI18N
        jtbToallas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbToallasItemStateChanged(evt);
            }
        });

        btgTipoRopa.add(jtbSabanas);
        jtbSabanas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/SABANAS2-removebg-preview.png"))); // NOI18N
        jtbSabanas.setBorderPainted(false);
        jtbSabanas.setContentAreaFilled(false);
        jtbSabanas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/SABANAS1-removebg-preview.png"))); // NOI18N
        jtbSabanas.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/SABANAS3-removebg-preview.png"))); // NOI18N
        jtbSabanas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbSabanasItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbDeportiva, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbBlanca, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbToallas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbSabanas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jtbToallas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtbSabanas, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jtbColor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtbBlanca, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtbDeportiva, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(0, 125));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Suciedad de la ropa");
        jLabel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel7.setBackground(new java.awt.Color(190, 178, 255));

        btgSuciedadRopa.add(jtbExtSucia);
        jtbExtSucia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/EXTSUCIA2-removebg-preview.png"))); // NOI18N
        jtbExtSucia.setBorderPainted(false);
        jtbExtSucia.setContentAreaFilled(false);
        jtbExtSucia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/EXTSUCIA1-removebg-preview.png"))); // NOI18N
        jtbExtSucia.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/EXTSUCIA3-removebg-preview.png"))); // NOI18N
        jtbExtSucia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbExtSuciaItemStateChanged(evt);
            }
        });

        btgSuciedadRopa.add(jtbSucia);
        jtbSucia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/SUCIA2-removebg-preview.png"))); // NOI18N
        jtbSucia.setBorderPainted(false);
        jtbSucia.setContentAreaFilled(false);
        jtbSucia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/SUCIA1-removebg-preview.png"))); // NOI18N
        jtbSucia.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/SUCIA3-removebg-preview.png"))); // NOI18N
        jtbSucia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbSuciaItemStateChanged(evt);
            }
        });

        btgSuciedadRopa.add(jtbMuySucia);
        jtbMuySucia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/MUYSUCIA2-removebg-preview.png"))); // NOI18N
        jtbMuySucia.setBorderPainted(false);
        jtbMuySucia.setContentAreaFilled(false);
        jtbMuySucia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/MUYSUCIA1-removebg-preview.png"))); // NOI18N
        jtbMuySucia.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/MUYSUCIA3-removebg-preview.png"))); // NOI18N
        jtbMuySucia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbMuySuciaItemStateChanged(evt);
            }
        });

        btgSuciedadRopa.add(jtbPocoSucia);
        jtbPocoSucia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/PSUCIA2-removebg-preview.png"))); // NOI18N
        jtbPocoSucia.setBorderPainted(false);
        jtbPocoSucia.setContentAreaFilled(false);
        jtbPocoSucia.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/PSUCIA1-removebg-preview.png"))); // NOI18N
        jtbPocoSucia.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/PSUCIA3-removebg-preview.png"))); // NOI18N
        jtbPocoSucia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbPocoSuciaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbExtSucia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbSucia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbPocoSucia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbMuySucia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbExtSucia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbMuySucia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbSucia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbPocoSucia, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cantidad de ropa");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel8.setBackground(new java.awt.Color(190, 178, 255));

        btgCantidadRopa.add(jtbMasiva);
        jtbMasiva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/MASIVA2-removebg-preview.png"))); // NOI18N
        jtbMasiva.setBorderPainted(false);
        jtbMasiva.setContentAreaFilled(false);
        jtbMasiva.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/MASIVA1-removebg-preview.png"))); // NOI18N
        jtbMasiva.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/MASIVA3-removebg-preview.png"))); // NOI18N
        jtbMasiva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbMasivaItemStateChanged(evt);
            }
        });

        btgCantidadRopa.add(jtbGrande);
        jtbGrande.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/GRANDE2-removebg-preview.png"))); // NOI18N
        jtbGrande.setBorderPainted(false);
        jtbGrande.setContentAreaFilled(false);
        jtbGrande.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/GRANDE1-removebg-preview.png"))); // NOI18N
        jtbGrande.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/GRANDE3-removebg-preview.png"))); // NOI18N
        jtbGrande.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbGrandeItemStateChanged(evt);
            }
        });

        btgCantidadRopa.add(jtbMediana);
        jtbMediana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/MEDIANA2-removebg-preview.png"))); // NOI18N
        jtbMediana.setBorderPainted(false);
        jtbMediana.setContentAreaFilled(false);
        jtbMediana.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/MEDIANA1-removebg-preview.png"))); // NOI18N
        jtbMediana.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/MEDIANA3-removebg-preview.png"))); // NOI18N
        jtbMediana.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbMedianaItemStateChanged(evt);
            }
        });

        btgCantidadRopa.add(jtbPequena);
        jtbPequena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/PEQUENA2-removebg-preview.png"))); // NOI18N
        jtbPequena.setBorderPainted(false);
        jtbPequena.setContentAreaFilled(false);
        jtbPequena.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/PEQUENA1-removebg-preview.png"))); // NOI18N
        jtbPequena.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/PEQUENA3-removebg-preview.png"))); // NOI18N
        jtbPequena.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbPequenaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbMasiva, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbPequena, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbMasiva, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtbPequena, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtbMediana, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(201, 215, 255));

        jtbTempFria.setBackground(new java.awt.Color(255, 255, 204));
        btgTempRopa.add(jtbTempFria);
        jtbTempFria.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jtbTempFria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/FRIA2-removebg-preview.png"))); // NOI18N
        jtbTempFria.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtbTempFria.setBorderPainted(false);
        jtbTempFria.setContentAreaFilled(false);
        jtbTempFria.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/FRIA1-removebg-preview.png"))); // NOI18N
        jtbTempFria.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/FRIA3-removebg-preview.png"))); // NOI18N
        jtbTempFria.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbTempFriaItemStateChanged(evt);
            }
        });

        jtbTempCalida.setBackground(new java.awt.Color(255, 255, 204));
        btgTempRopa.add(jtbTempCalida);
        jtbTempCalida.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jtbTempCalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/CALIDA2-removebg-preview.png"))); // NOI18N
        jtbTempCalida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtbTempCalida.setBorderPainted(false);
        jtbTempCalida.setContentAreaFilled(false);
        jtbTempCalida.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/CALIDA1-removebg-preview.png"))); // NOI18N
        jtbTempCalida.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/CALIDA3-removebg-preview.png"))); // NOI18N
        jtbTempCalida.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbTempCalidaItemStateChanged(evt);
            }
        });

        jtbTempTemplada.setBackground(new java.awt.Color(255, 255, 204));
        btgTempRopa.add(jtbTempTemplada);
        jtbTempTemplada.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jtbTempTemplada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/TEMP2-removebg-preview.png"))); // NOI18N
        jtbTempTemplada.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtbTempTemplada.setBorderPainted(false);
        jtbTempTemplada.setContentAreaFilled(false);
        jtbTempTemplada.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/TEMP1-removebg-preview.png"))); // NOI18N
        jtbTempTemplada.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/TEMP3-removebg-preview.png"))); // NOI18N
        jtbTempTemplada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtbTempTempladaItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Temperatura");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jtbTempCalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtbTempTemplada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtbTempFria))
                        .addGap(11, 11, 11))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtbTempFria, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtbTempCalida, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtbTempTemplada, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(172, 212, 245));

        jlblTiempoLavado.setBackground(new java.awt.Color(0, 0, 0));
        jlblTiempoLavado.setForeground(new java.awt.Color(51, 255, 102));
        jlblTiempoLavado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTiempoLavado.setText("00:00");
        jlblTiempoLavado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlblTiempoLavado.setOpaque(true);

        jlblTiempoEnjuague.setBackground(new java.awt.Color(0, 0, 0));
        jlblTiempoEnjuague.setForeground(new java.awt.Color(51, 255, 102));
        jlblTiempoEnjuague.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTiempoEnjuague.setText("00:00");
        jlblTiempoEnjuague.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlblTiempoEnjuague.setOpaque(true);

        jlblRPM.setBackground(new java.awt.Color(0, 0, 0));
        jlblRPM.setForeground(new java.awt.Color(51, 255, 102));
        jlblRPM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblRPM.setText("0000");
        jlblRPM.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlblRPM.setOpaque(true);

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tiempo de enjuague");
        jLabel9.setOpaque(true);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Tiempo de Lavado");
        jLabel8.setOpaque(true);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("RPM");
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblTiempoLavado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTiempoEnjuague, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblRPM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlblRPM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTiempoLavado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlblTiempoEnjuague, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jtgbInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/3.png"))); // NOI18N
        jtgbInicio.setBorderPainted(false);
        jtgbInicio.setContentAreaFilled(false);
        jtgbInicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/2.png"))); // NOI18N
        jtgbInicio.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/botonesiconos/1.png"))); // NOI18N
        jtgbInicio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtgbInicioItemStateChanged(evt);
            }
        });

        jbtnMostrarReglas.setBackground(new java.awt.Color(204, 204, 255));
        jbtnMostrarReglas.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 14)); // NOI18N
        jbtnMostrarReglas.setText("Mostrar reglas");
        jbtnMostrarReglas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnMostrarReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMostrarReglasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtgbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnMostrarReglas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jtgbInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnMostrarReglas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtbTempFriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbTempFriaItemStateChanged
        // TODO add your handling code here:
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            fria = true;
            temperatura = azar.nextInt( 23 ) + 15.5;
        } else {
            fria = false;
            
        }
    }//GEN-LAST:event_jtbTempFriaItemStateChanged

    private void jtbTempCalidaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbTempCalidaItemStateChanged
        // TODO add your handling code here:
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            calida = true;
            temperatura = azar.nextInt( 37 ) + 19.5; 
        } else {
            calida = false;
            
        }
    }//GEN-LAST:event_jtbTempCalidaItemStateChanged

    private void jtbTempTempladaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbTempTempladaItemStateChanged
        // TODO add your handling code here:
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            templada = true;
            temperatura = azar.nextInt( 24 ) + 37.5; 
        } else {
            templada = false;
            
        }
    }//GEN-LAST:event_jtbTempTempladaItemStateChanged

    private void jtbColorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbColorItemStateChanged
        // TODO add your handling code here:
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            color = true;
            tipoDeRopa = azar.nextDouble() * 0.25;
        } else {
            color = false;
            
        }
    }//GEN-LAST:event_jtbColorItemStateChanged

    private void jtbToallasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbToallasItemStateChanged
       if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            toallas = true;
            tipoDeRopa = ( azar.nextDouble() * 0.4 ) + 0.50;
        } else {
            
        }
    }//GEN-LAST:event_jtbToallasItemStateChanged

    private void jtbBlancaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbBlancaItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            blanca = true;
            tipoDeRopa = ( azar.nextDouble() * 0.40 ) + 0.07;
        } else {
            
        }
    }//GEN-LAST:event_jtbBlancaItemStateChanged

    private void jtbDeportivaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbDeportivaItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            deportiva = true;
            tipoDeRopa = ( azar.nextDouble() * 0.45 ) + 0.25;
        } else {
            
        }
    }//GEN-LAST:event_jtbDeportivaItemStateChanged

    private void jtbSabanasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbSabanasItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            sabanas = true;
            tipoDeRopa = ( azar.nextDouble() * 0.3 ) + 0.7;
        } else {
            
        }
    }//GEN-LAST:event_jtbSabanasItemStateChanged

    private void jtbExtSuciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbExtSuciaItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            extremadamenteSucia = true;
            suciedad = ( azar.nextDouble() * 0.36 ) + 0.64;
        } else {
            extremadamenteSucia = false;
        }
    }//GEN-LAST:event_jtbExtSuciaItemStateChanged

    private void jtbMuySuciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbMuySuciaItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            muySucia = true;
            suciedad = ( azar.nextDouble() * 0.56 ) + 0.34;
        } else {
            muySucia = false;
        }
    }//GEN-LAST:event_jtbMuySuciaItemStateChanged

    private void jtbSuciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbSuciaItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            sucia = true;
            suciedad = ( azar.nextDouble() * 0.54 ) + 0.1;
        } else {
            sucia = false;
        }
    }//GEN-LAST:event_jtbSuciaItemStateChanged

    private void jtbPocoSuciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbPocoSuciaItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            pocoSucia = true;
            suciedad = azar.nextDouble() * 0.34;
        } else {
            pocoSucia = false;
        }
    }//GEN-LAST:event_jtbPocoSuciaItemStateChanged

    private void jtbMasivaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbMasivaItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            masiva = true;
            cantidadRopa = azar.nextInt( 8 ) + 14;
        } else {
            masiva = false;
        }
    }//GEN-LAST:event_jtbMasivaItemStateChanged

    private void jtbGrandeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbGrandeItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            grande = true;
            cantidadRopa = azar.nextInt( 12 ) + 8;
        } else {
            grande = false;
        }
    }//GEN-LAST:event_jtbGrandeItemStateChanged

    private void jtbMedianaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbMedianaItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            mediana = true;
            cantidadRopa = azar.nextInt( 12 ) + 2;
        } else {
            mediana = false;
        }
    }//GEN-LAST:event_jtbMedianaItemStateChanged

    private void jtbPequenaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtbPequenaItemStateChanged
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            pequena = true;
            cantidadRopa = azar.nextInt( 9 );
        } else {
            pequena = false;
        }
    }//GEN-LAST:event_jtbPequenaItemStateChanged

    private void jtgbInicioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtgbInicioItemStateChanged
        // TODO add your handling code here:
        if ( evt.getStateChange() == ItemEvent.SELECTED ) {
            tipoColor = FuncionesMembresia.membershipTriangular(tipoDeRopa, 0.0, 0.0, 0.25);
            tipoBlanca = FuncionesMembresia.membershipTriangular(tipoDeRopa, 0.07, 0.25, 0.47); 
            tipoDeportiva = FuncionesMembresia.membershipTriangular(tipoDeRopa, 0.25, 0.47, 0.7);
            tipoToallas = FuncionesMembresia.membershipTriangular(tipoDeRopa, 0.508, 0.71372, 0.901);
            tipoSabanas = FuncionesMembresia.membershipTriangular(tipoDeRopa, 0.7, 1.0, 1);
            
            pSucia = FuncionesMembresia.membershipTriangular(suciedad, 0.0, 0.0, 0.34);
            _sucia = FuncionesMembresia.membershipTriangular(suciedad, 0.1, 0.34, 0.64);
            mSucia = FuncionesMembresia.membershipTriangular(suciedad, 0.34, 0.64, 0.9);
            eSucia = FuncionesMembresia.membershipTriangular(suciedad, 0.64, 1.0, 1.0);
            
            cantPequena = FuncionesMembresia.membershipTriangular(cantidadRopa, 0.0, 0.0, 8.0);
            cantMediana = FuncionesMembresia.membershipTriangular(cantidadRopa, 2.0, 8.0, 14.0);
            cantGrande = FuncionesMembresia.membershipTriangular(cantidadRopa, 8.0, 14.0, 20.0);
            cantMasiva = FuncionesMembresia.membershipTriangular(cantidadRopa, 14.0, 22.0, 22.0);
            
            tempFria = FuncionesMembresia.membershipTriangular(temperatura, 15.0, 15.0, 37.5);
            tempCalida = FuncionesMembresia.membershipTriangular(temperatura, 37.5, 60.0, 60.0);
            tempTemplada = FuncionesMembresia.membershipTriangular(temperatura, 19.5, 37.5, 55.5);
            
            // Definicion de reglas
            double r1 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantPequena ),tempFria);
            double r2 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantPequena ),tempCalida);
            double r3 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantPequena ),tempTemplada);
            double r4 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantMediana ),tempFria);
            double r5 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantMediana ),tempCalida);
            double r6 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantMediana ),tempTemplada);
            double r7 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantGrande ),tempFria);
            double r8 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantGrande ),tempCalida);
            double r9 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantGrande ),tempTemplada);
            double r10 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantMasiva ),tempFria);
            double r11 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantMasiva ),tempCalida);
            double r12 = Math.min( Math.min( Math.min( tipoColor, pSucia ), cantMasiva ),tempTemplada);
            double r13 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantPequena ),tempFria);
            double r14 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantPequena ),tempCalida);
            double r15 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantPequena ),tempTemplada);
            double r16 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantMediana ),tempFria);
            double r17 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantMediana ),tempCalida);
            double r18 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantMediana ),tempTemplada);
            double r19 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantGrande ),tempFria);
            double r20 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantGrande ),tempCalida);
            double r21 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantGrande ),tempTemplada);
            double r22 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantMasiva ),tempFria);
            double r23 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantMasiva ),tempCalida);
            double r24 = Math.min( Math.min( Math.min( tipoColor, _sucia ), cantMasiva ),tempTemplada);
            double r25 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantPequena ),tempFria);
            double r26 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantPequena ),tempCalida);
            double r27 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantPequena ),tempTemplada);
            double r28 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantMediana ),tempFria);
            double r29 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantMediana ),tempCalida);
            double r30 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantMediana ),tempTemplada);
            double r31 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantGrande ),tempFria);
            double r32 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantGrande ),tempCalida);
            double r33 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantGrande ),tempTemplada);
            double r34 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantMasiva ),tempFria);
            double r35 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantMasiva ),tempCalida);
            double r36 = Math.min( Math.min( Math.min( tipoColor, mSucia ), cantMasiva ),tempTemplada);
            double r37 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantPequena ),tempFria);
            double r38 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantPequena ),tempCalida);
            double r39 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantPequena ),tempTemplada);
            double r40 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantMediana ),tempFria);
            double r41 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantMediana ),tempCalida);
            double r42 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantMediana ),tempTemplada);
            double r43 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantGrande ),tempFria);
            double r44 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantGrande ),tempCalida);
            double r45 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantGrande ),tempTemplada);
            double r46 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantMasiva ),tempFria);
            double r47 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantMasiva ),tempCalida);
            double r48 = Math.min( Math.min( Math.min( tipoColor, eSucia ), cantMasiva ),tempTemplada);
            double r49 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantPequena ),tempFria);
            double r50 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantPequena ),tempCalida);
            double r51 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantPequena ),tempTemplada);
            double r52 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantMediana ),tempFria);
            double r53 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantMediana ),tempCalida);
            double r54 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantMediana ),tempTemplada);
            double r55 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantGrande ),tempFria);
            double r56 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantGrande ),tempCalida);
            double r57 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantGrande ),tempTemplada);
            double r58 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantMasiva ),tempFria);
            double r59 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantMasiva ),tempCalida);
            double r60 = Math.min( Math.min( Math.min( tipoBlanca, pSucia ), cantMasiva ),tempTemplada);
            double r61 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantPequena ),tempFria);
            double r62 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantPequena ),tempCalida);
            double r63 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantPequena ),tempTemplada);
            double r64 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantMediana ),tempFria);
            double r65 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantMediana ),tempCalida);
            double r66 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantMediana ),tempTemplada);
            double r67 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantGrande ),tempFria);
            double r68 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantGrande ),tempCalida);
            double r69 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantGrande ),tempTemplada);
            double r70 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantMasiva ),tempFria);
            double r71 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantMasiva ),tempCalida);
            double r72 = Math.min( Math.min( Math.min( tipoBlanca, _sucia ), cantMasiva ),tempTemplada);
            double r73 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantPequena ),tempFria);
            double r74 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantPequena ),tempCalida);
            double r75 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantPequena ),tempTemplada);
            double r76 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantMediana ),tempFria);
            double r77 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantMediana ),tempCalida);
            double r78 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantMediana ),tempTemplada);
            double r79 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantGrande ),tempFria);
            double r80 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantGrande ),tempCalida);
            double r81 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantGrande ),tempTemplada);
            double r82 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantMasiva ),tempFria);
            double r83 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantMasiva ),tempCalida);
            double r84 = Math.min( Math.min( Math.min( tipoBlanca, mSucia ), cantMasiva ),tempTemplada);
            double r85 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantPequena ),tempFria);
            double r86 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantPequena ),tempCalida);
            double r87 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantPequena ),tempTemplada);
            double r88 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantMediana ),tempFria);
            double r89 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantMediana ),tempCalida);
            double r90 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantMediana ),tempTemplada);
            double r91 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantGrande ),tempFria);
            double r92 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantGrande ),tempCalida);
            double r93 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantGrande ),tempTemplada);
            double r94 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantMasiva ),tempFria);
            double r95 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantMasiva ),tempCalida);
            double r96 = Math.min( Math.min( Math.min( tipoBlanca, eSucia ), cantMasiva ),tempTemplada);
            double r97 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantPequena ),tempFria);
            double r98 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantPequena ),tempCalida);
            double r99 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantPequena ),tempTemplada);
            double r100 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantMediana ),tempFria);
            double r101 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantMediana ),tempCalida);
            double r102 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantMediana ),tempTemplada);
            double r103 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantGrande ),tempFria);
            double r104 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantGrande ),tempCalida);
            double r105 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantGrande ),tempTemplada);
            double r106 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantMasiva ),tempFria);
            double r107 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantMasiva ),tempCalida);
            double r108 = Math.min( Math.min( Math.min( tipoDeportiva, pSucia ), cantMasiva ),tempTemplada);
            double r109 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantPequena ),tempFria);
            double r110 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantPequena ),tempCalida);
            double r111 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantPequena ),tempTemplada);
            double r112 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantMediana ),tempFria);
            double r113 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantMediana ),tempCalida);
            double r114 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantMediana ),tempTemplada);
            double r115 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantGrande ),tempFria);
            double r116 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantGrande ),tempCalida);
            double r117 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantGrande ),tempTemplada);
            double r118 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantMasiva ),tempFria);
            double r119 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantMasiva ),tempCalida);
            double r120 = Math.min( Math.min( Math.min( tipoDeportiva, _sucia ), cantMasiva ),tempTemplada);
            double r121 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantPequena ),tempFria);
            double r122 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantPequena ),tempCalida);
            double r123 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantPequena ),tempTemplada);
            double r124 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantMediana ),tempFria);
            double r125 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantMediana ),tempCalida);
            double r126 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantMediana ),tempTemplada);
            double r127 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantGrande ),tempFria);
            double r128 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantGrande ),tempCalida);
            double r129 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantGrande ),tempTemplada);
            double r130 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantMasiva ),tempFria);
            double r131 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantMasiva ),tempCalida);
            double r132 = Math.min( Math.min( Math.min( tipoDeportiva, mSucia ), cantMasiva ),tempTemplada);
            double r133 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantPequena ),tempFria);
            double r134 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantPequena ),tempCalida);
            double r135 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantPequena ),tempTemplada);
            double r136 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantMediana ),tempFria);
            double r137 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantMediana ),tempCalida);
            double r138 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantMediana ),tempTemplada);
            double r139 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantGrande ),tempFria);
            double r140 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantGrande ),tempCalida);
            double r141 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantGrande ),tempTemplada);
            double r142 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantMasiva ),tempFria);
            double r143 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantMasiva ),tempCalida);
            double r144 = Math.min( Math.min( Math.min( tipoDeportiva, eSucia ), cantMasiva ),tempTemplada);
            double r145 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantPequena ),tempFria);
            double r146 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantPequena ),tempCalida);
            double r147 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantPequena ),tempTemplada);
            double r148 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantMediana ),tempFria);
            double r149 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantMediana ),tempCalida);
            double r150 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantMediana ),tempTemplada);
            double r151 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantGrande ),tempFria);
            double r152 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantGrande ),tempCalida);
            double r153 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantGrande ),tempTemplada);
            double r154 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantMasiva ),tempFria);
            double r155 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantMasiva ),tempCalida);
            double r156 = Math.min( Math.min( Math.min( tipoToallas, pSucia ), cantMasiva ),tempTemplada);
            double r157 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantPequena ),tempFria);
            double r158 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantPequena ),tempCalida);
            double r159 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantPequena ),tempTemplada);
            double r160 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantMediana ),tempFria);
            double r161 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantMediana ),tempCalida);
            double r162 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantMediana ),tempTemplada);
            double r163 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantGrande ),tempFria);
            double r164 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantGrande ),tempCalida);
            double r165 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantGrande ),tempTemplada);
            double r166 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantMasiva ),tempFria);
            double r167 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantMasiva ),tempCalida);
            double r168 = Math.min( Math.min( Math.min( tipoToallas, _sucia ), cantMasiva ),tempTemplada);
            double r169 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantPequena ),tempFria);
            double r170 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantPequena ),tempCalida);
            double r171 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantPequena ),tempTemplada);
            double r172 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantMediana ),tempFria);
            double r173 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantMediana ),tempCalida);
            double r174 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantMediana ),tempTemplada);
            double r175 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantGrande ),tempFria);
            double r176 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantGrande ),tempCalida);
            double r177 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantGrande ),tempTemplada);
            double r178 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantMasiva ),tempFria);
            double r179 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantMasiva ),tempCalida);
            double r180 = Math.min( Math.min( Math.min( tipoToallas, mSucia ), cantMasiva ),tempTemplada);
            double r181 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantPequena ),tempFria);
            double r182 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantPequena ),tempCalida);
            double r183 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantPequena ),tempTemplada);
            double r184 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantMediana ),tempFria);
            double r185 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantMediana ),tempCalida);
            double r186 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantMediana ),tempTemplada);
            double r187 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantGrande ),tempFria);
            double r188 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantGrande ),tempCalida);
            double r189 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantGrande ),tempTemplada);
            double r190 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantMasiva ),tempFria);
            double r191 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantMasiva ),tempCalida);
            double r192 = Math.min( Math.min( Math.min( tipoToallas, eSucia ), cantMasiva ),tempTemplada);
            double r193 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantPequena ),tempFria);
            double r194 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantPequena ),tempCalida);
            double r195 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantPequena ),tempTemplada);
            double r196 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantMediana ),tempFria);
            double r197 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantMediana ),tempCalida);
            double r198 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantMediana ),tempTemplada);
            double r199 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantGrande ),tempFria);
            double r200 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantGrande ),tempCalida);
            double r201 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantGrande ),tempTemplada);
            double r202 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantMasiva ),tempFria);
            double r203 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantMasiva ),tempCalida);
            double r204 = Math.min( Math.min( Math.min( tipoSabanas, pSucia ), cantMasiva ),tempTemplada);
            double r205 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantPequena ),tempFria);
            double r206 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantPequena ),tempCalida);
            double r207 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantPequena ),tempTemplada);
            double r208 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantMediana ),tempFria);
            double r209 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantMediana ),tempCalida);
            double r210 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantMediana ),tempTemplada);
            double r211 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantGrande ),tempFria);
            double r212 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantGrande ),tempCalida);
            double r213 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantGrande ),tempTemplada);
            double r214 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantMasiva ),tempFria);
            double r215 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantMasiva ),tempCalida);
            double r216 = Math.min( Math.min( Math.min( tipoSabanas, _sucia ), cantMasiva ),tempTemplada);
            double r217 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantPequena ),tempFria);
            double r218 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantPequena ),tempCalida);
            double r219 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantPequena ),tempTemplada);
            double r220 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantMediana ),tempFria);
            double r221 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantMediana ),tempCalida);
            double r222 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantMediana ),tempTemplada);
            double r223 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantGrande ),tempFria);
            double r224 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantGrande ),tempCalida);
            double r225 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantGrande ),tempTemplada);
            double r226 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantMasiva ),tempFria);
            double r227 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantMasiva ),tempCalida);
            double r228 = Math.min( Math.min( Math.min( tipoSabanas, mSucia ), cantMasiva ),tempTemplada);
            double r229 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantPequena ),tempFria);
            double r230 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantPequena ),tempCalida);
            double r231 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantPequena ),tempTemplada);
            double r232 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantMediana ),tempFria);
            double r233 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantMediana ),tempCalida);
            double r234 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantMediana ),tempTemplada);
            double r235 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantGrande ),tempFria);
            double r236 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantGrande ),tempCalida);
            double r237 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantGrande ),tempTemplada);
            double r238 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantMasiva ),tempFria);
            double r239 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantMasiva ),tempCalida);
            double r240 = Math.min( Math.min( Math.min( tipoSabanas, eSucia ), cantMasiva ),tempTemplada);
            
            lavadoMCorto = FuncionesMembresia.membershipTrapezoidal(rpmBajo, 0.0, 0.0, 5.0, 10.0);
            lavadoCorto = FuncionesMembresia.membershipTriangular(rpmBajo, 0.0, 14.0, 41.0);
            lavadoMedio = FuncionesMembresia.membershipTriangular(rpmBajo, 11.0, 30.0, 44.0);
            lavadoLargo = FuncionesMembresia.membershipTriangular(rpmBajo, 23.0, 47.0, 60.0);
            lavadoMLargo = FuncionesMembresia.membershipTrapezoidal(rpmBajo, 50.0, 55.0, 60.0, 60.0);
            
            enjuagueMCorto = FuncionesMembresia.membershipTrapezoidal(rpmBajo, 0.0, 0.0, 5.0, 10.0);
            enjuagueCorto = FuncionesMembresia.membershipTriangular(rpmBajo, 0.0, 14.0, 41.0);
            enjuagueMedio = FuncionesMembresia.membershipTriangular(rpmBajo, 11.0, 30.0, 44.0);
            enjuagueLargo = FuncionesMembresia.membershipTriangular(rpmBajo, 23.0, 47.0, 60.0);
            enjuagueMLargo = FuncionesMembresia.membershipTrapezoidal(rpmBajo, 50.0, 55.0, 60.0, 60.0);
            
            rpmMLento = FuncionesMembresia.membershipTrapezoidal(rpmBajo, 0.0, 400.0, 600.0, 900.0);
            rpmBajo = FuncionesMembresia.membershipTriangular(rpmBajo, 550.0, 850.0, 1170.0);
            rpmMedio = FuncionesMembresia.membershipTriangular(rpmBajo, 800.0, 1170.0, 1570.0);
            rpmRapido = FuncionesMembresia.membershipTriangular(rpmBajo, 1180.0, 1501.0, 1780.0);
            rpmMRapido = FuncionesMembresia.membershipTrapezoidal(rpmBajo, 1400.0, 1700.0, 2000.0, 2000.0);
        }
    }//GEN-LAST:event_jtgbInicioItemStateChanged

    private void jbtnMostrarReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMostrarReglasActionPerformed
        // TODO add your handling code here:
        PanelReglasActivadas panel = new PanelReglasActivadas();
        
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        frame.getContentPane().add(panel);
        frame.setTitle("Reglas activadas");
        
        frame.pack();
        
        frame.setVisible( true );
        
    }//GEN-LAST:event_jbtnMostrarReglasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameLavadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameLavadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameLavadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameLavadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameLavadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCantidadRopa;
    private javax.swing.ButtonGroup btgSuciedadRopa;
    private javax.swing.ButtonGroup btgTempRopa;
    private javax.swing.ButtonGroup btgTipoRopa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton jbtnMostrarReglas;
    private javax.swing.JLabel jlblRPM;
    private javax.swing.JLabel jlblTiempoEnjuague;
    private javax.swing.JLabel jlblTiempoLavado;
    private javax.swing.JToggleButton jtbBlanca;
    private javax.swing.JToggleButton jtbColor;
    private javax.swing.JToggleButton jtbDeportiva;
    private javax.swing.JToggleButton jtbExtSucia;
    private javax.swing.JToggleButton jtbGrande;
    private javax.swing.JToggleButton jtbMasiva;
    private javax.swing.JToggleButton jtbMediana;
    private javax.swing.JToggleButton jtbMuySucia;
    private javax.swing.JToggleButton jtbPequena;
    private javax.swing.JToggleButton jtbPocoSucia;
    private javax.swing.JToggleButton jtbSabanas;
    private javax.swing.JToggleButton jtbSucia;
    private javax.swing.JToggleButton jtbTempCalida;
    private javax.swing.JToggleButton jtbTempFria;
    private javax.swing.JToggleButton jtbTempTemplada;
    private javax.swing.JToggleButton jtbToallas;
    private javax.swing.JToggleButton jtgbInicio;
    // End of variables declaration//GEN-END:variables
}
